name: Test Runners
on: [workflow_dispatch]
jobs:
  test-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ubuntu works"
      - run: uname -a
  test-macos14:
    runs-on: macos-14
    steps:
      - run: echo "macos-14 works"
      - run: uname -a
      - run: xcodebuild -version
  test-macos13:
    runs-on: macos-13
    steps:
      - run: echo "macos-13 works"
      - run: uname -a
      - run: xcodebuild -version
